#!/usr/bin/env bash
#
# setup the Vim Configuration of Champions

info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

echo ''
info 'Setting up the Vim Configuration of Champions'
info '============================================='
echo ''

info 'Installing Vundle'
info '-----------------'
git clone git://github.com/gmarik/vundle.git bundle/vundle

info 'Setting up Symlinks'
info '--------------'
mkdir -p ~/.config
ln -s ~/.vim ~/.config/nvim
info 'Created link from ~/.config/nvim to ~/.vim'

info 'Installing plugins'
info '-------------------------------------------------'
if test $(which nvim)
then
  nvim --headless +PluginInstall +qall
else
  fail 'nvim or vim not found in path.'
fi

success 'Setup complete. Run vim and enjoy'
